# Generated by Django 4.1.5 on 2023-01-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=40)),
                ('card_cvv', models.PositiveIntegerField()),
                ('total_value', models.FloatField()),
                ('extra_description', models.CharField(max_length=50, null=True)),
                ('comission_value', models.FloatField()),
            ],
        ),
    ]
